// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hdhyqwcyrvuuumqspiei.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhkaHlxd2N5cnZ1dXVtcXNwaWVpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxNTg2NzMsImV4cCI6MjA2NDczNDY3M30.1Q6caSDQmqf-9Y79nk241oQOTD5ypPcp5VnFpzg_yhg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);